// ── Add or remove games here ──────────────────────────────────────────────────
// Each entry: { name: 'Display Name', url: 'https://...' }

export const games = [
  { name: 'Cookie Clicker',                   url: 'https://cookieclicker-nu.vercel.app' },
  { name: 'Drive Mad',                         url: 'https://drive-mad1.vercel.app' },
  { name: 'Eaglercraft 1.8',                  url: 'https://eagler1-8-8-wasm-gc.vercel.app' },
  { name: 'Eaglercraft 1.12',                 url: 'https://math-class-school.vercel.app' },
  { name: 'House of Hazards',                  url: 'https://house-of-hazards-ashy.vercel.app' },
  { name: 'Dadish 1',                          url: 'https://dadish.vercel.app' },
  { name: 'Dadish 2',                          url: 'https://dadish2.vercel.app/' },
  { name: 'Dadish 3',                          url: 'https://dadish3-2.vercel.app/' },
  { name: 'Stickman Hook',                     url: 'https://stickman-hook-five.vercel.app' },
  { name: 'Bitlife',                           url: 'https://bitlife1.vercel.app' },
  { name: 'Getaway Shootout',                  url: 'https://getaway-shootout-ten.vercel.app/' },
  { name: 'Rooftop Snipers',                   url: 'https://rooftop-snipers-rose.vercel.app/' },
  { name: 'Basket Random',                     url: 'https://basket-random-ph7z.vercel.app/' },
  { name: 'GunSpin',                           url: 'https://gun-spin-dusky.vercel.app/' },
  { name: 'Slope',                             url: 'https://slope-game-fsq3.vercel.app/' },
  { name: 'Bongo Cat',                         url: 'https://bongo-cat-lyart.vercel.app/' },
  { name: 'Snow Rider 3D',                     url: 'https://snow-rider3-d-five.vercel.app/' },
  { name: 'Small World Cup',                   url: 'https://a-small-world-cup-eight.vercel.app/' },
  { name: 'Vex 5',                             url: 'https://vex5-sigma.vercel.app/' },
  { name: 'Vex 6',                             url: 'https://vex6-nine.vercel.app/' },
  { name: 'Block Blast',                       url: 'https://block-blast-tau.vercel.app/' },
  { name: 'Slowroads.io',                      url: 'https://slow-roads-psi.vercel.app/' },
  { name: 'Amazing Strange Rope Police',       url: 'https://amazing-strange-rope-police-eight.vercel.app/' },
  { name: 'Geometry Dash (Scratch)',           url: 'https://gd-ten-jet.vercel.app/' },
  { name: 'Flappy Bird',                       url: 'https://flappy-bird-three-nu.vercel.app/' },
  { name: 'EmulatorJS',                        url: 'https://emulator-js-sigma.vercel.app/' },
  { name: 'Hollow Knight',                     url: 'https://hollow-knight-red.vercel.app/' },
  { name: 'Deltarune Chapter 1',               url: 'https://deltarune-1.vercel.app/' },
  { name: 'Deltarune Chapter 2',               url: 'https://deltarune-2.vercel.app/' },
  { name: 'Deltarune Chapter 3',               url: 'https://deltarune-3.vercel.app/' },
  { name: 'Undertale',                         url: 'https://undertale-2.vercel.app/' },
  { name: 'Five Nights At Epsteins',           url: 'https://fnae-2.vercel.app/' },
  { name: 'Brotato',                           url: 'https://brotato-1.vercel.app/' },
  { name: 'Polytrack',                         url: 'https://poly-test-five.vercel.app/' },
  { name: 'Bad Time Simulator',                url: 'https://bad-time-sim.vercel.app' },
  { name: 'Ragdoll Archers',                   url: 'https://rag-archers.vercel.app/' },
  { name: 'Retro Bowl',                        url: 'https://freegamesunblocked76.github.io/retro-bowl/' },
  { name: 'Stardew Valley',                    url: 'https://stardew-valley-iframe.vercel.app/' },
  { name: 'RedRoom',                           url: 'https://heartfelt-croquembouche-c0e7a0.netlify.app/' },
  { name: 'Slither.io',                        url: 'https://gulper.io/' },
  { name: 'Cuphead',                           url: 'https://dwdvil.github.io/cuphead-cdv-web/' },
  { name: 'Crossy Road',                       url: 'https://tangerine-lebkuchen-1330f1.netlify.app/' },
  { name: 'Get Yolked',                        url: 'https://euphonious-narwhal-02b68c.netlify.app/' },
  { name: 'FNAF',                              url: 'https://irv77.github.io/hd_fnaf/1/' },
  { name: '1v1.lol',                           url: 'https://lolygames.github.io/1v1-lol/?v=20251120014815' },
  { name: 'Bendy and the Ink Machine',         url: 'https://map-l.github.io/play/bendy-and-the-ink-machine/' },
  { name: 'Slime Rancher',                     url: 'https://enchanting-sorbet-464cd5.netlify.app/' },
  { name: 'Ships 3D',                          url: 'https://symphonious-dieffenbachia-0c2d1d.netlify.app/' },
  { name: 'Tanks 3D',                          url: 'https://effortless-sawine-4f7574.netlify.app/' },
  { name: 'Dynamic AI',                        url: 'https://groq-nvidia.koyeb.app/' },
  { name: 'Drive Mad Mind (Wifi off after launch)', url: 'https://devi-iframe-2.vercel.app/' },
  { name: 'Buckshot Roulette (laggy)',         url: 'https://bksht-rlt.vercel.app/' },
  { name: 'Balatro',                           url: 'https://balatro-gray.vercel.app/' },
  { name: 'Drift Hunters',                     url: 'https://drift-hunters-green.vercel.app' },
  { name: 'Silksong (Very Slow)',              url: 'https://silksong-alpha.vercel.app/' },
  { name: 'Idle Breakout',                     url: 'https://idle-breakout-jz7b.vercel.app/' },
  { name: 'Gladihoppers',                      url: 'https://gladihoppers-sepia.vercel.app/' },
  { name: 'Minecraft Portable',                url: 'https://mc-portable.vercel.app/' },
  { name: 'Sandboxels',                        url: 'https://sandboxels-zeta-lyart.vercel.app/' },
  { name: 'Peppa Pig Simulator',              url: 'https://pp-iframe.vercel.app/' },
  { name: 'Karlson',                           url: 'https://karlson-alpha.vercel.app/' },
  { name: 'Dadish 3D',                         url: 'https://d3-d-iframe.vercel.app/' },
  { name: 'Granny',                            url: 'https://granny-sigma.vercel.app/' },
  { name: 'Brotato Paws & Claws (Slow Start)', url: 'https://bp-c-w.vercel.app/' },
];

export const testingGames = [
  { name: 'GTA Vice City',    url: 'https://gta-vice-city-chi.vercel.app/' },
  { name: 'There Is No Game', url: 'https://there-is-no-game-pink.vercel.app/' },
  { name: 'Boom Slingers',    url: 'https://boom-slingers.vercel.app/' },
  { name: 'Coreball',         url: 'https://coreball-cyan.vercel.app/' },
  { name: 'Tunnel Rush',      url: 'https://tunnel-rush-jade.vercel.app/' },
  { name: 'Bowmasters',       url: 'https://bowmasters-three.vercel.app/' },
];

export const proxies = [
  // { name: 'My Proxy', url: 'https://...' },
];
